name: dnapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_hooks:
  hooks_riverpod:
  velocity_x:
  freezed_annotation:
  json_serializable:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint:
  build_runner:
  freezed:

flutter:
  uses-material-design: true
